#! /bin/sh
if [ "$1" == "start" ]; then
	iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
	iptables -A FORWARD -i eth0 -o wlan0 -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
	iptables -A FORWARD -i wlan0 -o eth0 -j ACCEPT

	hostapd -B /etc/hostapd/hostapd.conf
fi
