name: Build

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependency
      run: sudo apt install -y help2man

    - name: Make
      run: |
        cd buildroot
        mv ../.config .
        mv ../.config_linux .
        mv ../rootfs_overlay .
        make

    - name: Compress output directory
      run: |
        mkdir -p artifacts
        cd buildroot/output/images
        tar -cf - rootfs.cpio.zst bzImage | zstd -19 -T0 > ../../../artifacts/output.tar.zst

    - name: Create GitHub release and upload compressed file
      env: 
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        RELEASE_TAG="release-$(date +'%Y%m%d%H%M%S')"
        gh release create "$RELEASE_TAG" artifacts/output.tar.zst \
          --title "Automated Release $RELEASE_TAG" \
          --notes "This is an automated release. Contains the compressed output directory."
