name: Build

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependency
      run: sudo apt install -y help2man && rm -rf output

    - name: Make
      run: cd buildroot && make

    - name: Compress output directory
      run: |
        mkdir -p artifacts
        cd buildroot/output/images
        tar -cf - rootfs.cpio.zst bzImage | zstd -T0 > ../../../artifacts/output.tar.zst

    - name: Create GitHub release and upload compressed file
      env: 
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        RELEASE_TAG="release-$(date +'%Y%m%d%H%M%S')"
        gh release create "$RELEASE_TAG" artifacts/output.tar.zst \
          --title "Automated Release $RELEASE_TAG" \
          --notes "This is an automated release. Contains the compressed output directory."

    - name: Delete artifacts directory
      run: |
        rm -rf artifacts

    - name: Find and delete files larger than 100MB (recursive)
      run: |
        find . -type f -size +100M -exec rm -f {} +

    - name: Commit and push changes
      run: |
        git pull
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Make & Remove files larger than 100MB"
        git push
