name: Config
on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Mv config
      run: |
        cd buildroot
        mv ../.config .
        mv ../.config_linux .
        mv ../rootfs_overlay .

    - name: Prepare kernel config
      run: cd buildroot && make linux-menuconfig || true
      
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3

    - name: Commit
      run: |
        cd buildroot
        mv .config ../
        mv .config_linux ../
        mv rootfs_overlay ../
        cd ../
        git pull
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .config .config_linux rootfs_overlay
        git commit -m "Automated commit via GitHub Actions"
        git push
